### ISSUE TITLE
How to understand the 'pool_local' operation during KPConv

### ISSUE THREAD

**Issue by whu-lyh** [yzdad/D-GLSNet#6]
Hi, I am confused about the operation at [here](https://github.com/yzdad/D-GLSNet/blob/05bc10f76143f2ea1c4361ddb2dd0ab560143f51/models/backbone/kpconv_fpn.py#L263). I wander what is the usage of this operation? "plane='xy'" corresponding to what?
```
feats_s1_out = self.layer1_out(feats_s1).unsqueeze(0)
index_1 = coordinate2index(normalize_coordinate(points_list[0].clone().unsqueeze(0), plane='xy',padding=self.padding), self.reso_plane * 8)
pooled_s1 = self.pool_local(index_1, feats_s1_out, self.reso_plane * 8).squeeze(0)
feats_s1 = torch.cat([feats_s1, pooled_s1], dim=1)
```
Can you give me some advices? Thanks.

**Comment by yzdad** [comment]
This operation is not very useful for our open source configuration, so it is not mentioned in the paper. This operation is to expect points with similar (x, y) coordinates and different z coordinates to have relatively similar characteristics. You can refer to the literature "Convolutional Occupancy Networks"

**Comment by whu-lyh** [comment]
Thanks, I am quite confused to this part, LoL. I will check this paper~
